#!/usr/bin/env tsx
/**
 * CLI for the **v2** AI code-review agent (OpenRouter TypeScript SDK).
 *
 * Mirrors the v1 CLI but routes through reviewDiffV2 (native json_schema output
 * via @openrouter/sdk). v1 (tools/ai-review/cli.ts) is left untouched.
 *
 * Usage:
 *   npm run review:v2 -- --diff tools/ai-review/fixtures/sql-injection.diff
 *   npm run review:v2 -- --git origin/main
 *   git diff | npm run review:v2
 *
 * Flags: --json  --comment <file>  --junit <file>  --timeout <sec>  --model <id>  --no-fail  --verbose|-v
 *
 * Requires OPENROUTER_API_KEY (the v2 SDK path has no mock — use v1 for keyless demos).
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { reviewDiffV2 } from "./reviewAgentV2";
import { REVIEW_DIMENSIONS, type ReviewVerdict } from "../schema";

const USAGE = `Usage:
  npm run review:v2 -- --diff <file>     review a diff file
  npm run review:v2 -- --git [base]      review changes vs a ref (default: origin/main → auto)
  git diff | npm run review:v2           review a piped diff

Flags: --json  --comment <file>  --junit <file>  --timeout <sec>  --model <id>  --attempts <n>  --no-fail  --verbose|-v
Requires OPENROUTER_API_KEY.
`;

function loadEnv(): void {
  const load = (process as NodeJS.Process & { loadEnvFile?: (p: string) => void }).loadEnvFile;
  for (const f of [".env.local", ".env"]) {
    try {
      load?.(f);
    } catch {
      /* missing — fine */
    }
  }
}
loadEnv();

const arg = (name: string): string | undefined => {
  const i = process.argv.indexOf(name);
  return i !== -1 ? process.argv[i + 1] : undefined;
};
const has = (name: string): boolean => process.argv.includes(name);
const note = (m: string): void => void process.stderr.write(`[ai-review v2] ${m}\n`);

function git(args: string[]): string {
  return execFileSync("git", args, { encoding: "utf8", maxBuffer: 10 * 1024 * 1024 });
}
function refExists(ref: string): boolean {
  try {
    execFileSync("git", ["rev-parse", "--verify", "-q", ref], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}
function resolveBase(explicit?: string): string | undefined {
  let remote: string | undefined;
  try {
    remote = git(["remote"]).split("\n").map((s) => s.trim()).filter(Boolean)[0];
  } catch {
    /* no remote */
  }
  return [explicit, "origin/main", remote && `${remote}/main`, "main", "master"]
    .filter((r): r is string => !!r)
    .find(refExists);
}
function loadDiff(): string {
  const diffFile = arg("--diff");
  if (diffFile) return readFileSync(diffFile, "utf8");
  if (has("--git")) {
    const explicit = arg("--git") && !arg("--git")!.startsWith("--") ? arg("--git") : undefined;
    const base = resolveBase(explicit);
    if (base) {
      const committed = git(["diff", `${base}...HEAD`]);
      if (committed.trim()) return committed;
    }
    return git(["diff", "HEAD"]);
  }
  if (process.stdin.isTTY) {
    process.stderr.write(USAGE);
    process.exit(2);
  }
  try {
    return readFileSync(0, "utf8");
  } catch {
    return "";
  }
}

function toMarkdown(v: ReviewVerdict, model: string, degraded: boolean): string {
  const rows = REVIEW_DIMENSIONS.map((d) => `| ${d} | ${v[d]}/10 |`).join("\n");
  const findings =
    v.findings && v.findings.length
      ? "\n\n**Findings**\n" +
        v.findings.map((f) => `- \`${f.severity}\`${f.file ? ` ${f.file}` : ""}: ${f.note}`).join("\n")
      : "";
  return `### ${v.verdict === "pass" ? "✅" : "❌"} AI Code Review (v2) — **${v.verdict.toUpperCase()}**${
    degraded ? " _(degraded: failing closed)_" : ""
  }

${v.summary}

| Dimension | Score |
| --- | --- |
${rows}${findings}

<sub>Generated by the 10xChampion AI reviewer **v2** (OpenRouter SDK, model: \`${model}\`). Rubric: \`tools/ai-review/criteria.md\`.</sub>`;
}

function xmlEscape(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function toJUnit(v: ReviewVerdict, model: string): string {
  const cases: { cls: string; name: string; fail?: string }[] = [];
  for (const d of REVIEW_DIMENSIONS) {
    const t = d === "securitySafety" ? 5 : 3;
    cases.push({ cls: "ai-review.v2.dimensions", name: `${d} (${v[d]}/10)`, fail: v[d] <= t ? `score ${v[d]} <= ${t}` : undefined });
  }
  for (const f of v.findings ?? [])
    cases.push({
      cls: "ai-review.v2.findings",
      name: `[${f.severity}] ${f.file ?? "general"}`,
      fail: f.severity === "blocker" || f.severity === "major" ? f.note : undefined,
    });
  cases.push({ cls: "ai-review.v2", name: `verdict: ${v.verdict}`, fail: v.verdict === "fail" ? v.summary : undefined });
  const failures = cases.filter((c) => c.fail).length;
  const body = cases
    .map(
      (c) =>
        `    <testcase classname="${xmlEscape(c.cls)}" name="${xmlEscape(c.name)}" time="0">${
          c.fail ? `\n      <failure message="${xmlEscape(c.fail)}"></failure>` : ""
        }\n    </testcase>`,
    )
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="AI Code Review v2" tests="${cases.length}" failures="${failures}">
  <testsuite name="AI Code Review v2 (${xmlEscape(model)})" tests="${cases.length}" failures="${failures}">
${body}
  </testsuite>
</testsuites>
`;
}

async function main() {
  const verbose = has("--verbose") || has("-v");
  const diff = loadDiff();
  const timeoutArg = arg("--timeout") ?? process.env.AI_REVIEW_TIMEOUT;
  const timeoutMs = timeoutArg ? Math.max(1, Number(timeoutArg)) * 1000 : undefined;

  const attemptsArg = arg("--attempts");
  const { verdict, model, degraded, usage } = await reviewDiffV2(diff, {
    onEvent: verbose ? note : undefined,
    timeoutMs,
    model: arg("--model"),
    maxAttempts: attemptsArg ? Math.max(1, Number(attemptsArg)) : undefined,
  });

  if (usage) note(`usage: in=${usage.inputTokens ?? "?"} out=${usage.outputTokens ?? "?"}${usage.costUsd != null ? ` cost=$${usage.costUsd}` : ""}`);

  const markdown = toMarkdown(verdict, model, degraded);
  const commentFile = arg("--comment");
  if (commentFile) writeFileSync(commentFile, markdown, "utf8");
  const junitFile = arg("--junit");
  if (junitFile) writeFileSync(junitFile, toJUnit(verdict, model), "utf8");

  process.stdout.write((has("--json") ? JSON.stringify(verdict, null, 2) : markdown) + "\n");

  if (verdict.verdict === "fail" && !has("--no-fail")) finish(1);
}

/**
 * Set the exit code and let the event loop drain so the OpenRouter SDK's
 * sockets/timers close cleanly. A calling `process.exit()` while a libuv handle
 * is still closing crashes on Windows (UV_HANDLE_CLOSING assertion). The unref'd
 * timer is a backstop that force-exits only if keep-alive sockets linger.
 */
function finish(code: number): void {
  process.exitCode = code;
  setTimeout(() => process.exit(code), 500).unref();
}

main().catch((err) => {
  console.error("AI review v2 failed:", err instanceof Error ? err.message : err);
  finish(2);
});
