#!/usr/bin/env tsx
/**
 * CLI for the **v3** AI code-review agent (Vercel AI SDK tool-loop).
 *
 * Unlike v2 (single scorer), v3 may read repo files for context before scoring,
 * and reports which files it read + how many steps it took.
 *
 * Usage:
 *   npm run review:v3 -- --diff tools/ai-review/fixtures/sql-injection.diff
 *   npm run review:v3 -- --git origin/main
 *   git diff | npm run review:v3
 *
 * Flags: --json  --comment <file>  --timeout <sec>  --model <id>  --no-fail  --verbose|-v
 * Requires OPENROUTER_API_KEY (real SDK, no mock — use v1 for keyless demos).
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { reviewDiffV3 } from "./reviewAgentV3";
import { filterDiff } from "../filterDiff";
import { REVIEW_DIMENSIONS, type ReviewVerdict } from "../schema";

const USAGE = `Usage:
  npm run review:v3 -- --diff <file>     review a diff file
  npm run review:v3 -- --git [base]      review changes vs a ref (default: origin/main → auto)
  git diff | npm run review:v3           review a piped diff

Flags: --json  --comment <file>  --timeout <sec>  --model <id>  --no-fail  --verbose|-v
Requires OPENROUTER_API_KEY.
`;

function loadEnv(): void {
  const load = (
    process as NodeJS.Process & { loadEnvFile?: (p: string) => void }
  ).loadEnvFile;
  for (const f of [".env.local", ".env"]) {
    try {
      load?.(f);
    } catch {
      /* missing — fine */
    }
  }
}
loadEnv();

const arg = (name: string): string | undefined => {
  const i = process.argv.indexOf(name);
  return i !== -1 ? process.argv[i + 1] : undefined;
};
const has = (name: string): boolean => process.argv.includes(name);
const note = (m: string): void =>
  void process.stderr.write(`[ai-review v3] ${m}\n`);

function git(args: string[]): string {
  return execFileSync("git", args, {
    encoding: "utf8",
    maxBuffer: 10 * 1024 * 1024,
  });
}
function refExists(ref: string): boolean {
  try {
    execFileSync("git", ["rev-parse", "--verify", "-q", ref], {
      stdio: "ignore",
    });
    return true;
  } catch {
    return false;
  }
}
function resolveBase(explicit?: string): string | undefined {
  let remote: string | undefined;
  try {
    remote = git(["remote"])
      .split("\n")
      .map((s) => s.trim())
      .filter(Boolean)[0];
  } catch {
    /* no remote */
  }
  return [explicit, "origin/main", remote && `${remote}/main`, "main", "master"]
    .filter((r): r is string => !!r)
    .find(refExists);
}
function loadDiff(): string {
  const diffFile = arg("--diff");
  if (diffFile) return readFileSync(diffFile, "utf8");
  if (has("--git")) {
    const explicit =
      arg("--git") && !arg("--git")!.startsWith("--")
        ? arg("--git")
        : undefined;
    const base = resolveBase(explicit);
    if (base) {
      const committed = git(["diff", `${base}...HEAD`]);
      if (committed.trim()) return committed;
    }
    return git(["diff", "HEAD"]);
  }
  if (process.stdin.isTTY) {
    process.stderr.write(USAGE);
    process.exit(2);
  }
  try {
    return readFileSync(0, "utf8");
  } catch {
    return "";
  }
}

function toMarkdown(
  v: ReviewVerdict,
  model: string,
  degraded: boolean,
  filesRead: string[],
  steps: number,
): string {
  const rows = REVIEW_DIMENSIONS.map((d) => `| ${d} | ${v[d]}/10 |`).join("\n");
  const findings =
    v.findings && v.findings.length
      ? "\n\n**Findings**\n" +
        v.findings
          .map(
            (f) => `- \`${f.severity}\`${f.file ? ` ${f.file}` : ""}: ${f.note}`,
          )
          .join("\n")
      : "";
  const context = filesRead.length
    ? `\n\n<sub>🔎 Agent read ${filesRead.length} file(s) for context over ${steps} step(s): ${filesRead.map((f) => `\`${f}\``).join(", ")}.</sub>`
    : `\n\n<sub>Agent took ${steps} step(s); no extra context needed.</sub>`;
  return `### ${v.verdict === "pass" ? "✅" : "❌"} AI Code Review (v3) — **${v.verdict.toUpperCase()}**${
    degraded ? " _(degraded: failing closed)_" : ""
  }

${v.summary}

| Dimension | Score |
| --- | --- |
${rows}${findings}${context}

<sub>Generated by the 10xChampion AI reviewer **v3** (Vercel AI SDK tool-loop, model: \`${model}\`). Rubric: \`tools/ai-review/criteria.md\`.</sub>`;
}

async function main() {
  const verbose = has("--verbose") || has("-v");
  const { filtered: diff, dropped } = filterDiff(loadDiff());
  if (dropped.length) {
    note(
      `excluded ${dropped.length} non-code file(s): ${dropped.slice(0, 8).join(", ")}${dropped.length > 8 ? "…" : ""}`,
    );
  }

  const files = (diff.match(/^diff --git /gm) || []).length;
  note(`reviewing ${files} file(s), ${diff ? diff.split("\n").length : 0} diff lines…`);

  const timeoutArg = arg("--timeout") ?? process.env.AI_REVIEW_TIMEOUT;
  const timeoutMs = timeoutArg
    ? Math.max(1, Number(timeoutArg)) * 1000
    : undefined;

  const { verdict, model, degraded, usage, filesRead, steps } =
    await reviewDiffV3(diff, {
      onEvent: verbose ? note : undefined,
      timeoutMs,
      model: arg("--model"),
    });

  if (usage)
    note(
      `usage: in=${usage.inputTokens ?? "?"} out=${usage.outputTokens ?? "?"}${usage.costUsd != null ? ` cost=$${usage.costUsd}` : ""}`,
    );

  const markdown = toMarkdown(verdict, model, degraded, filesRead, steps);
  const commentFile = arg("--comment");
  if (commentFile) writeFileSync(commentFile, markdown, "utf8");

  process.stdout.write(
    (has("--json") ? JSON.stringify(verdict, null, 2) : markdown) + "\n",
  );

  if (verdict.verdict === "fail" && !has("--no-fail")) finish(1);
}

/** Let the event loop drain so SDK sockets close cleanly before exiting (Windows libuv). */
function finish(code: number): void {
  process.exitCode = code;
  setTimeout(() => process.exit(code), 500).unref();
}

main().catch((err) => {
  console.error("AI review v3 failed:", err instanceof Error ? err.message : err);
  finish(2);
});
